# EDA for Sales

## Setup

In [1]:
import pandas as pd 
import numpy as np 

import matplotlib.pyplot as plt 
import seaborn as sns
import plotly.express as px

## Import Data

In [2]:
holidays = pd.read_csv("../../datasets/holidays_events.csv")
oil = pd.read_csv("../../datasets/oil.csv")
stores = pd.read_csv("../../datasets/stores.csv")
transactions = pd.read_csv("../../datasets/transactions.csv") 

train = pd.read_csv("../../datasets/train.csv")
test = pd.read_csv("../../datasets/test.csv")


holidays["date"] = pd.to_datetime(holidays["date"])
oil["date"] = pd.to_datetime(oil["date"])
transactions["date"] = pd.to_datetime(transactions["date"])

train["date"] = pd.to_datetime(train["date"])
test["date"] = pd.to_datetime(test["date"])

## Exploratory Data Analysis

### Stores.csv

In [3]:
stores

    store_nbr           city                           state type  cluster
0           1          Quito                       Pichincha    D       13
1           2          Quito                       Pichincha    D       13
2           3          Quito                       Pichincha    D        8
3           4          Quito                       Pichincha    D        9
4           5  Santo Domingo  Santo Domingo de los Tsachilas    D        4
5           6          Quito                       Pichincha    D       13
6           7          Quito                       Pichincha    D        8
7           8          Quito                       Pichincha    D        8
8           9          Quito                       Pichincha    B        6
9          10          Quito                       Pichincha    C       15
10         11        Cayambe                       Pichincha    B        6
11         12      Latacunga                        Cotopaxi    C       15
12         13      Latacunga                        Cotopaxi    C       15
13         14       Riobamba                      Chimborazo    C        7
14         15         Ibarra                        Imbabura    C       15
15         16  Santo Domingo  Santo Domingo de los Tsachilas    C        3
16         17          Quito                       Pichincha    C       12
17         18          Quito                       Pichincha    B       16
18         19       Guaranda                         Bolivar    C       15
19         20          Quito                       Pichincha    B        6
20         21  Santo Domingo  Santo Domingo de los Tsachilas    B        6
21         22           Puyo                         Pastaza    C        7
22         23         Ambato                      Tungurahua    D        9
23         24      Guayaquil                          Guayas    D        1
24         25        Salinas                     Santa Elena    D        1
25         26      Guayaquil                          Guayas    D       10
26         27          Daule                          Guayas    D        1
27         28      Guayaquil                          Guayas    E       10
28         29      Guayaquil                          Guayas    E       10
29         30      Guayaquil                          Guayas    C        3
30         31       Babahoyo                        Los Rios    B       10
31         32      Guayaquil                          Guayas    C        3
32         33        Quevedo                        Los Rios    C        3
33         34      Guayaquil                          Guayas    B        6
34         35         Playas                          Guayas    C        3
35         36       Libertad                          Guayas    E       10
36         37         Cuenca                           Azuay    D        2
37         38           Loja                            Loja    D        4
38         39         Cuenca                           Azuay    B        6
39         40        Machala                          El Oro    C        3
40         41        Machala                          El Oro    D        4
41         42         Cuenca                           Azuay    D        2
42         43     Esmeraldas                      Esmeraldas    E       10
43         44          Quito                       Pichincha    A        5
44         45          Quito                       Pichincha    A       11
45         46          Quito                       Pichincha    A       14
46         47          Quito                       Pichincha    A       14
47         48          Quito                       Pichincha    A       14
48         49          Quito                       Pichincha    A       11
49         50         Ambato                      Tungurahua    A       14
50         51      Guayaquil                          Guayas    A       17
51         52          Manta                          Manabi    A       11
52         53          Manta                          Manabi    D       13
53         54      El Carmen                          Manabi    C        3

In [4]:
transactions.groupby("store_nbr")["transactions"].sum().reset_index()

    store_nbr  transactions
0           1       2553963
1           2       3219901
2           3       5366350
3           4       2519007
4           5       2347877
5           6       3065896
6           7       2995993
7           8       4637971
8           9       3516162
9          10       1652493
10         11       3972488
11         12       1958852
12         13       1572504
13         14       2287850
14         15       2209898
15         16       1464498
16         17       2295485
17         18       2071278
18         19       2107489
19         20       1422539
20         21        842891
21         22        504156
22         23       1788171
23         24       3568206
24         25       1520362
25         26       1065059
26         27       2485687
27         28       1957594
28         29        981448
29         30       1171130
30         31       2306044
31         32       1065226
32         33       1743003
33         34       3864018
34         35       1123889
35         36       1738129
36         37       2481719
37         38       2867052
38         39       2389482
39         40       2181195
40         41       1764146
41         42        802646
42         43       2182356
43         44       7273093
44         45       6201115
45         46       5990113
46         47       6535810
47         48       5107785
48         49       4574103
49         50       4384444
50         51       2873614
51         52        275393
52         53       1180082
53         54       1451290

In [5]:
temp_stores = stores.merge(transactions.groupby("store_nbr")["transactions"].sum().reset_index(), on="store_nbr")
temp_stores

,store_nbr,city,state,type,cluster,transactions
0,1,Quito,Pichincha,D,13,2553963
1,2,Quito,Pichincha,D,13,3219901
2,3,Quito,Pichincha,D,8,5366350
3,4,Quito,Pichincha,D,9,2519007
4,5,Santo Domingo,Santo Domingo de los Tsachilas,D,4,2347877
5,6,Quito,Pichincha,D,13,3065896
6,7,Quito,Pichincha,D,8,2995993
7,8,Quito,Pichincha,D,8,4637971
8,9,Quito,Pichincha,B,6,3516162
9,10,Quito,Pichincha,C,15,1652493
10,11,Cayambe,Pichincha,B,6,3972488
11,12,Latacunga,Cotopaxi,C,15,1958852
12,13,Latacunga,Cotopaxi,C,15,1572504
13,14,Riobamba,Chimborazo,C,7,2287850
14,15,Ibarra,Imbabura,C,15,2209898
15,16,Santo Domingo,Santo Domingo de los Tsachilas,C,3,1464498
16,17,Quito,Pichincha,C,12,2295485
17,18,Quito,Pichincha,B,16,2071278
18,19,Guaranda,Bolivar,C,15,2107489
19,20,Quito,Pichincha,B,6,1422539
20,21,Santo Domingo,Santo Domingo de los Tsachilas,B,6,842891
21,22,Puyo,Pastaza,C,7,504156
22,23,Ambato,Tungurahua,D,9,1788171
23,24,Guayaquil,Guayas,D,1,3568206
24,25,Salinas,Santa Elena,D,1,1520362
25,26,Guayaquil,Guayas,D,10,1065059
26,27,Daule,Guayas,D,1,2485687
27,28,Guayaquil,Guayas,E,10,1957594
28,29,Guayaquil,Guayas,E,10,981448
29,30,Guayaquil,Guayas,C,3,1171130
30,31,Babahoyo,Los Rios,B,10,2306044
31,32,Guayaquil,Guayas,C,3,1065226
32,33,Quevedo,Los Rios,C,3,1743003
33,34,Guayaquil,Guayas,B,6,3864018
34,35,Playas,Guayas,C,3,1123889
35,36,Libertad,Guayas,E,10,1738129
36,37,Cuenca,Azuay,D,2,2481719
37,38,Loja,Loja,D,4,2867052
38,39,Cuenca,Azuay,B,6,2389482
39,40,Machala,El Oro,C,3,2181195
40,41,Machala,El Oro,D,4,1764146
41,42,Cuenca,Azuay,D,2,802646
42,43,Esmeraldas,Esmeraldas,E,10,2182356
43,44,Quito,Pichincha,A,5,7273093
44,45,Quito,Pichincha,A,11,6201115
45,46,Quito,Pichincha,A,14,5990113
46,47,Quito,Pichincha,A,14,6535810
47,48,Quito,Pichincha,A,14,5107785
48,49,Quito,Pichincha,A,11,4574103
49,50,Ambato,Tungurahua,A,14,4384444
50,51,Guayaquil,Guayas,A,17,2873614
51,52,Manta,Manabi,A,11,275393
52,53,Manta,Manabi,D,13,1180082
53,54,El Carmen,Manabi,C,3,1451290

In [6]:
# Store Type Encoder
from sklearn.preprocessing import OrdinalEncoder

store_type_encoder = OrdinalEncoder()
temp_stores["type"] = store_type_encoder.fit_transform(temp_stores[["type"]])
temp_stores.corr(numeric_only=True)["transactions"].sort_values()

type           -0.456709
store_nbr       0.118950
cluster         0.206197
transactions    1.000000
Name: transactions, dtype: float64

In [7]:
# city / state encoding
from sklearn.preprocessing import OneHotEncoder

city_state_encoder = OneHotEncoder(sparse_output=False)

city_state_encoding_result = pd.DataFrame(city_state_encoder.fit_transform(temp_stores[["city", "state"]]), columns=city_state_encoder.get_feature_names_out())
city_state_encoding_result
pd.concat([temp_stores, city_state_encoding_result], axis="columns").corr(numeric_only=True)["transactions"].sort_values(ascending=True)

type                                   -0.456709
state_Manabi                           -0.253255
city_Manta                             -0.234698
state_Guayas                           -0.201399
city_Puyo                              -0.183807
state_Pastaza                          -0.183807
state_Santo Domingo de los Tsachilas   -0.163854
city_Santo Domingo                     -0.163854
city_Guayaquil                         -0.145507
city_Playas                            -0.129969
state_Azuay                            -0.111775
city_Cuenca                            -0.111775
state_Cotopaxi                         -0.105961
city_Latacunga                         -0.105961
city_El Carmen                         -0.101527
state_Santa Elena                      -0.095526
city_Salinas                           -0.095526
state_El Oro                           -0.080287
city_Machala                           -0.080287
city_Libertad                          -0.076609
city_Quevedo                           -0.076185
state_Los Rios                         -0.073856
city_Guaranda                          -0.044521
state_Bolivar                          -0.044521
state_Esmeraldas                       -0.038017
city_Esmeraldas                        -0.038017
state_Imbabura                         -0.035625
city_Ibarra                            -0.035625
state_Chimborazo                       -0.028853
city_Riobamba                          -0.028853
city_Babahoyo                          -0.027272
city_Daule                             -0.011666
state_Loja                              0.021464
city_Loja                               0.021464
state_Tungurahua                        0.057839
city_Ambato                             0.057839
city_Cayambe                            0.117496
store_nbr                               0.118950
cluster                                 0.206197
city_Quito                              0.592281
state_Pichincha                         0.617831
transactions                            1.000000
Name: transactions, dtype: float64

#### Итоги проверки гипотез

##### Подтвержденные гипотезы 

1. __Проверка связи между продажами магазина и его типом__

    Есть неплохая кореляция между продажами и типом магазина [-0.45], так что явно неплохой атрибут для обучения модели

2. __Проверка связи между продажами магазина и городом/штатом в котором они находятся__
    
    В зависимости от города, в котором находится магазин может наблюдаться хорошая кореляция с продажами, например если взять столицу Кито или нахождение магазина в штате Пичинча. Также некоторые города и штаты дают отрицательную кореляцию, так что в целом как будто бы что то с чем можно работать. Возможно стоит отставить только атрибут, который показывает, находится ли магазин в столице/штатет Пинчинча и может быть еще пару других городов и штатов которые дают неплохую отрицательную кореляцию, но об этом лучше еще подумать чутка

3. __Проверка связи между продажами магазина и его кластером__ 

    Кореляция 0.2 так что в целом непонятно, но теоретически можно взять