## Setup

In [1]:
import pandas as pd 
import numpy as np 

import matplotlib.pyplot as plt 
import seaborn as sns
import plotly.express as px

## Import Data

In [3]:
holidays = pd.read_csv("../../datasets/holidays_events.csv")
oil = pd.read_csv("../../datasets/oil.csv")
stores = pd.read_csv("../../datasets/stores.csv")
transactions = pd.read_csv("../../datasets/transactions.csv") 

train = pd.read_csv("../../datasets/train.csv")
test = pd.read_csv("../../datasets/test.csv")


holidays["date"] = pd.to_datetime(holidays["date"])
oil["date"] = pd.to_datetime(oil["date"])
transactions["date"] = pd.to_datetime(transactions["date"])

train["date"] = pd.to_datetime(train["date"])
test["date"] = pd.to_datetime(test["date"])

## Exploratory Data Analysis

### Holidays_events.csv

In [3]:
holidays

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False
...,...,...,...,...,...,...
345,2017-12-22,Additional,National,Ecuador,Navidad-3,False
346,2017-12-23,Additional,National,Ecuador,Navidad-2,False
347,2017-12-24,Additional,National,Ecuador,Navidad-1,False
348,2017-12-25,Holiday,National,Ecuador,Navidad,False
349,2017-12-26,Additional,National,Ecuador,Navidad+1,False

Transfered Holidays

In [4]:
holidays[holidays["transferred"] == True]

,date,type,locale,locale_name,description,transferred
19,2012-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
72,2013-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
135,2014-10-09,Holiday,National,Ecuador,Independencia de Guayaquil,True
255,2016-05-24,Holiday,National,Ecuador,Batalla de Pichincha,True
266,2016-07-25,Holiday,Local,Guayaquil,Fundacion de Guayaquil,True
268,2016-08-10,Holiday,National,Ecuador,Primer Grito de Independencia,True
297,2017-01-01,Holiday,National,Ecuador,Primer dia del ano,True
303,2017-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,True
312,2017-05-24,Holiday,National,Ecuador,Batalla de Pichincha,True
324,2017-08-10,Holiday,National,Ecuador,Primer Grito de Independencia,True
328,2017-09-28,Holiday,Local,Ibarra,Fundacion de Ibarra,True
340,2017-12-06,Holiday,Local,Quito,Fundacion de Quito,True

In [5]:
holidays[holidays["type"] == "Transfer"]

,date,type,locale,locale_name,description,transferred
20,2012-10-12,Transfer,National,Ecuador,Traslado Independencia de Guayaquil,False
73,2013-10-11,Transfer,National,Ecuador,Traslado Independencia de Guayaquil,False
136,2014-10-10,Transfer,National,Ecuador,Traslado Independencia de Guayaquil,False
256,2016-05-27,Transfer,National,Ecuador,Traslado Batalla de Pichincha,False
265,2016-07-24,Transfer,Local,Guayaquil,Traslado Fundacion de Guayaquil,False
269,2016-08-12,Transfer,National,Ecuador,Traslado Primer Grito de Independencia,False
298,2017-01-02,Transfer,National,Ecuador,Traslado Primer dia del ano,False
304,2017-04-13,Transfer,Local,Cuenca,Fundacion de Cuenca,False
313,2017-05-26,Transfer,National,Ecuador,Traslado Batalla de Pichincha,False
325,2017-08-11,Transfer,National,Ecuador,Traslado Primer Grito de Independencia,False
329,2017-09-29,Transfer,Local,Ibarra,Fundacion de Ibarra,False
342,2017-12-08,Transfer,Local,Quito,Traslado Fundacion de Quito,False

In [6]:
temp_holidays = holidays.copy()

In [7]:
temp_holidays.drop(temp_holidays[temp_holidays["type"] == "Transfer"].index, inplace=True)
temp_holidays

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False
...,...,...,...,...,...,...
345,2017-12-22,Additional,National,Ecuador,Navidad-3,False
346,2017-12-23,Additional,National,Ecuador,Navidad-2,False
347,2017-12-24,Additional,National,Ecuador,Navidad-1,False
348,2017-12-25,Holiday,National,Ecuador,Navidad,False
349,2017-12-26,Additional,National,Ecuador,Navidad+1,False

In [8]:
holidays_transactions = transactions.copy()

In [9]:
temp_holidays

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False
...,...,...,...,...,...,...
345,2017-12-22,Additional,National,Ecuador,Navidad-3,False
346,2017-12-23,Additional,National,Ecuador,Navidad-2,False
347,2017-12-24,Additional,National,Ecuador,Navidad-1,False
348,2017-12-25,Holiday,National,Ecuador,Navidad,False
349,2017-12-26,Additional,National,Ecuador,Navidad+1,False

In [10]:
holidays_transactions = holidays_transactions.merge(stores.loc[:, ["store_nbr", "city", "state"]], on="store_nbr")
holidays_transactions

            date  store_nbr  transactions       city        state
0     2013-01-01         25           770    Salinas  Santa Elena
1     2013-01-02          1          2111      Quito    Pichincha
2     2013-01-02          2          2358      Quito    Pichincha
3     2013-01-02          3          3487      Quito    Pichincha
4     2013-01-02          4          1922      Quito    Pichincha
...          ...        ...           ...        ...          ...
83483 2017-08-15         50          2804     Ambato   Tungurahua
83484 2017-08-15         51          1573  Guayaquil       Guayas
83485 2017-08-15         52          2255      Manta       Manabi
83486 2017-08-15         53           932      Manta       Manabi
83487 2017-08-15         54           802  El Carmen       Manabi

[83488 rows x 5 columns]

In [11]:
temp_holidays_local = temp_holidays[temp_holidays["locale"] == "Local"]
temp_holidays_regional = temp_holidays[temp_holidays["locale"] == "Regional"]
temp_holidays_national = temp_holidays[temp_holidays["locale"] == "National"]

In [12]:
temp_holidays["description"].unique()

array(['Fundacion de Manta', 'Provincializacion de Cotopaxi',
       'Fundacion de Cuenca', 'Cantonizacion de Libertad',
       'Cantonizacion de Riobamba', 'Cantonizacion del Puyo',
       'Cantonizacion de Guaranda', 'Provincializacion de Imbabura',
       'Cantonizacion de Latacunga', 'Fundacion de Machala',
       'Fundacion de Santo Domingo', 'Cantonizacion de El Carmen',
       'Cantonizacion de Cayambe', 'Fundacion de Esmeraldas',
       'Primer Grito de Independencia', 'Fundacion de Riobamba',
       'Fundacion de Ambato', 'Fundacion de Ibarra',
       'Cantonizacion de Quevedo', 'Independencia de Guayaquil',
       'Dia de Difuntos', 'Independencia de Cuenca',
       'Provincializacion de Santo Domingo',
       'Provincializacion Santa Elena', 'Independencia de Guaranda',
       'Independencia de Latacunga', 'Independencia de Ambato',
       'Fundacion de Quito-1', 'Fundacion de Quito', 'Fundacion de Loja',
       'Navidad-4', 'Cantonizacion de Salinas', 'Navidad-3', 'Navidad-2',
       'Puente Navidad', 'Navidad-1', 'Navidad', 'Navidad+1',
       'Puente Primer dia del ano', 'Primer dia del ano-1',
       'Primer dia del ano', 'Recupero puente Navidad',
       'Recupero puente primer dia del ano', 'Carnaval', 'Viernes Santo',
       'Dia del Trabajo', 'Dia de la Madre-1', 'Dia de la Madre',
       'Batalla de Pichincha', 'Fundacion de Guayaquil-1',
       'Fundacion de Guayaquil', 'Inauguracion Mundial de futbol Brasil',
       'Mundial de futbol Brasil: Ecuador-Suiza',
       'Mundial de futbol Brasil: Ecuador-Honduras',
       'Mundial de futbol Brasil: Ecuador-Francia',
       'Mundial de futbol Brasil: Octavos de Final',
       'Mundial de futbol Brasil: Cuartos de Final',
       'Mundial de futbol Brasil: Semifinales',
       'Mundial de futbol Brasil: Tercer y cuarto lugar',
       'Mundial de futbol Brasil: Final', 'Black Friday', 'Cyber Monday',
       'Recupero Puente Navidad', 'Recupero Puente Primer dia del ano',
       'Terremoto Manabi', 'Terremoto Manabi+1', 'Terremoto Manabi+2',
       'Terremoto Manabi+3', 'Terremoto Manabi+4', 'Terremoto Manabi+5',
       'Terremoto Manabi+6', 'Terremoto Manabi+7', 'Terremoto Manabi+8',
       'Terremoto Manabi+9', 'Terremoto Manabi+10', 'Terremoto Manabi+11',
       'Terremoto Manabi+12', 'Terremoto Manabi+13',
       'Terremoto Manabi+14', 'Terremoto Manabi+15',
       'Terremoto Manabi+16', 'Terremoto Manabi+17',
       'Terremoto Manabi+18', 'Terremoto Manabi+19',
       'Terremoto Manabi+20', 'Terremoto Manabi+21',
       'Terremoto Manabi+22', 'Terremoto Manabi+23',
       'Terremoto Manabi+24', 'Terremoto Manabi+25',
       'Terremoto Manabi+26', 'Terremoto Manabi+27',
       'Terremoto Manabi+28', 'Terremoto Manabi+29',
       'Terremoto Manabi+30', 'Puente Dia de Difuntos',
       'Recupero Puente Dia de Difuntos'], dtype=object)

In order to test the following hypothesis we need to :
1. merge dataframes `stores` and `transactions` by store number
2. divide the `holidays` dataframe into smaller ones based on locality and for each holiday create a column
3. fill these columns accordingly
4. determine correlations
5. select the best ones as potential attributes

In [13]:
def holidays_transformations_v0(holidays:pd.DataFrame, df:pd.DataFrame):
    
    holidays.drop(holidays[holidays["transferred"] == True].index, inplace=True)
    free_days = holidays[holidays["type"] != "Work Day"]  

    local_holidays = free_days[free_days["locale"] == "Local"]
    regional_holidays = free_days[free_days["locale"] == "Regional"]
    national_holidays = free_days[free_days["locale"] == "National"]


    for idx in range(0, local_holidays.shape[0]):
        df.loc[(df["date"] == local_holidays.iloc[idx]["date"]) & 
            (df["city"] == local_holidays.iloc[idx]["locale_name"]), local_holidays.iloc[idx]["description"]] = 1

    for idx in range(0, regional_holidays.shape[0]):
        df.loc[(df["date"] == regional_holidays.iloc[idx]["date"]) & 
           (df["state"] == regional_holidays.iloc[idx]["locale_name"]), regional_holidays.iloc[idx]["description"]] = 1
        
    for idx in range(0, national_holidays.shape[0]):
        df.loc[df["date"] == national_holidays.iloc[idx]["date"], national_holidays.iloc[idx]["description"]] = 1


    df = df.fillna(0)

    return df

In [14]:
preprocessed_holidays_v0 = holidays_transformations_v0(holidays, transactions.merge(stores, on="store_nbr"))

C:\Users\masam\AppData\Local\Temp\ipykernel_19864\653599595.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[df["date"] == national_holidays.iloc[idx]["date"], national_holidays.iloc[idx]["description"]] = 1
C:\Users\masam\AppData\Local\Temp\ipykernel_19864\653599595.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[df["date"] == national_holidays.iloc[idx]["date"], national_holidays.iloc[idx]["description"]] = 1

In [15]:
preprocessed_holidays_v0.corr(numeric_only=True)["transactions"].sort_values(ascending=True)

Fundacion de Guayaquil-1      -0.011016
Carnaval                      -0.010851
Fundacion de Guayaquil        -0.008618
Fundacion de Santo Domingo    -0.008596
Terremoto Manabi+12           -0.008322
                                 ...
store_nbr                      0.189311
cluster                        0.196014
transactions                   1.000000
Traslado Fundacion de Quito         NaN
Navidad                             NaN
Name: transactions, Length: 101, dtype: float64

At this point we can say that the previous hypothesis has failed and does not give us any conclusions or possible useful attributes, so let's move on to testing the last hypothesis.

In [16]:
holidays

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False
...,...,...,...,...,...,...
345,2017-12-22,Additional,National,Ecuador,Navidad-3,False
346,2017-12-23,Additional,National,Ecuador,Navidad-2,False
347,2017-12-24,Additional,National,Ecuador,Navidad-1,False
348,2017-12-25,Holiday,National,Ecuador,Navidad,False
349,2017-12-26,Additional,National,Ecuador,Navidad+1,False

In [17]:
def holidays_transformations(holidays:pd.DataFrame, df:pd.DataFrame):
    holidays.drop(holidays[holidays["transferred"] == True].index, inplace=True)
    work_days = holidays[holidays["type"] == "Work Day"]
    free_days = holidays[holidays["type"] != "Work Day"]  


    local_holidays = free_days[free_days["locale"] == "Local"]
    regional_holidays = free_days[free_days["locale"] == "Regional"]
    national_holidays = free_days[free_days["locale"] == "National"]

    local_workdays = work_days[work_days["locale"] == "Local"]
    regional_workdays = work_days[work_days["locale"] == "Regional"]
    national_workdays = work_days[work_days["locale"] == "National"]
 
    df["is_Holiday"] = 0

    for idx in range(0, local_holidays.shape[0]):
        df.loc[(df["date"] == local_holidays.iloc[idx]["date"]) & 
            (df["city"] == local_holidays.iloc[idx]["locale_name"]), "is_Holiday"] = 1

    for idx in range(0, regional_holidays.shape[0]):
        df.loc[(df["date"] == regional_holidays.iloc[idx]["date"]) & 
            (df["state"] == regional_holidays.iloc[idx]["locale_name"]), "is_Holiday"] = 1
        
    for idx in range(0, national_holidays.shape[0]):
        df.loc[df["date"] ==national_holidays.iloc[idx]["date"], "is_Holiday"]= 1

    return df

In [18]:
preprocessed_holidays = holidays_transformations(holidays, transactions.merge(stores, on="store_nbr"))
preprocessed_holidays

,date,store_nbr,transactions,city,state,type,cluster,is_Holiday
0,2013-01-01,25,770,Salinas,Santa Elena,D,1,1
1,2013-01-02,1,2111,Quito,Pichincha,D,13,0
2,2013-01-02,2,2358,Quito,Pichincha,D,13,0
3,2013-01-02,3,3487,Quito,Pichincha,D,8,0
4,2013-01-02,4,1922,Quito,Pichincha,D,9,0
...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,Ambato,Tungurahua,A,14,0
83484,2017-08-15,51,1573,Guayaquil,Guayas,A,17,0
83485,2017-08-15,52,2255,Manta,Manabi,A,11,0
83486,2017-08-15,53,932,Manta,Manabi,D,13,0
83487,2017-08-15,54,802,El Carmen,Manabi,C,3,0

In [19]:
for i in range(0, 55):
    print(i, "-", preprocessed_holidays[preprocessed_holidays["store_nbr"] == i].corr(numeric_only=True)["transactions"]["is_Holiday"])

0 - nan
1 - -0.14301159089720109
2 - 0.26767160640564835
3 - 0.25814868135287294
4 - 0.2862306708456483
5 - 0.14764133872837268
6 - 0.30906959931736244
7 - 0.10349646668669203
8 - 0.14941409595612223
9 - 0.2565522776256886
10 - 0.155514802054813
11 - 0.2342629756139009
12 - 0.2369163575029157
13 - 0.1744623137256907
14 - 0.04247634843191302
15 - 0.016256457176744846
16 - 0.1428586861187606
17 - 0.2769700961620433
18 - 0.05116086207114469
19 - 0.14312613949612352
20 - 0.23587384483254065
21 - 0.12995021379013366
22 - 0.2026317880190349
23 - 0.18934852264716368
24 - 0.018070266122289968
25 - 0.22884074619320544
26 - 0.19134549270511686
27 - 0.278320464180992
28 - 0.2518147618162478
29 - 0.19556045966933516
30 - 0.1317253696708451
31 - 0.27867575535376077
32 - 0.22140709947910228
33 - 0.1264813807081229
34 - 0.07637572195553202
35 - 0.2649080149729859
36 - 0.23586494022944005
37 - 0.10210940700321293
38 - 0.2098098996966001
39 - 0.203191556659383
40 - 0.04409102597484878
41 - 0.2825128846201538
42 - 0.1659955479671457
43 - 0.16473602728308448
44 - 0.24424895027517488
45 - 0.2687926555038815
46 - 0.272821870175037
47 - 0.27083582085978375
48 - 0.27487216240776596
49 - 0.27885467588082513
50 - 0.2506905667462475
51 - 0.27096099165633974
52 - 0.3571159534402465
53 - 0.2708711234007809
54 - 0.1939076445534541

### EDA Results

#### Future Attributes 

##### Transactions 
- Days of the week (bool)

##### Gas
- Gas price (float)

##### Stores
- Store type (a-e -> 0-4, int)
- Store cluster
- City and state they are located in (bool, onehot)

##### Holidays
- Was there a holiday on this day/holiday (bool, onehot)


#### Additional Notes
- remove data about April 2016 (earthquake)
- separately calculate stores that do not sell certain product families
- divide all data into 33 dataframes for each product family